version: '3.7'

services:
  app.bijak:
    restart: always
    image: 638615282713.dkr.ecr.ap-south-1.amazonaws.com/trade-service:prod
    container_name: trade-service-prod
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: final
      args:
        - env=prod
    volumes:
      - ..:/home/node/app
      - ~/.aws:/home/node/.aws:ro
    ports:
      - '3004:3004'
    stdin_open: true
    tty: true
    environment:
      - env=prod
      - DEBUG=true
    networks:
      - bijak_network
networks:
  bijak_network:
